format_version = 1
id = "overview_scene_group"
name = "Overview Scene Group"
object_type = "scene_group"
active = true

[components.Core]
name = "Overview Scene Group"
active = true
editing_color = [ 1, 1, 1, 1 ]

[components.SceneGroupInfo]
scene_group_title = "수배전반 개요"
scene_group_detail = "Overview Scene Group containing all overview scenes"
editing_color = [ 1, 1, 1, 1 ]
