format_version = 1
id = "poi_arrow_00"
name = "poi_arrow_00"
object_type = "image"
active = true

[components.Core]
name = "poi_arrow_00"
active = true
editing_color = [ 1, 1, 1, 1 ]

[components.Transform]
position = [ 1.5, 0.0, 0.0 ]
rotation = [ 0.0, 0.0, 0.0 ]
scale = [ 0.352, 0.568, 1.0 ]

[components.Resource]
resource_path = "poi_arrow_00.png"

[components.Image]
enable_interaction = true
