format_version = 1
id = "gnb_00"
name = "gnb_00"
object_type = "image"
active = true

[components.Core]
name = "gnb_00"
active = true
editing_color = [ 1, 1, 1, 1 ]

[components.Transform]
position = [ 0.0, 0.0, 0.0 ]
rotation = [ 0.0, 0.0, 0.0 ]
scale = [ 0.664, 0.884, 1.0 ]

[components.Resource]
resource_path = "gnb_00.png"

[components.Image]
enable_interaction = true
