format_version = 1
id = "guide_00"
name = "guide_00"
object_type = "image"
active = true

[components.Core]
name = "guide_00"
active = true
editing_color = [ 1, 1, 1, 1 ]

[components.Transform]
position = [ 0.5, 0.0, 0.0 ]
rotation = [ 0.0, 0.0, 0.0 ]
scale = [ 0.7, 0.4, 1.0 ]

[components.Resource]
resource_path = "guide_00.png"

[components.Image]
enable_interaction = true
